### ISSUE TITLE
User Dropdown is missing

### ISSUE THREAD

**Issue by SelectiveAlso** [SelectiveAlso/mbcdb#2]
@Borgdude  There used to be a dropdown when you click on your username on the right side of the header. Now it won't show up when you click your username, so you can't access the admin panel or logout. 
![screen shot 2016-11-04 at 3 24 41 pm](https://cloud.githubusercontent.com/assets/15224976/20021211/dd590690-a2a2-11e6-973f-ebcd46d8ca61.png)

**Comment by Borgdude** [comment]
@SelectiveAlso It's still working for me.
![capture](https://cloud.githubusercontent.com/assets/6686189/20026162/dd0e9ade-a2c4-11e6-8565-a1c331fbc517.PNG)
